import os
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_core.prompts import PromptTemplate
from langchain_community.llms.fake import FakeListLLM
from ai_engine.llm.safety_auditor import SafetyAuditor

class RAGPipeline:
    def __init__(self):
        db_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'data', 'processed', 'chromadb')
        self.embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
        self.vectorstore = Chroma(persist_directory=db_dir, embedding_function=self.embeddings)
        self.llm = FakeListLLM(responses=[
            "Based on the retrieved clinical guidelines and the patient's specific EHR constraints (e.g. allergies, renal function), here is the recommended safe treatment protocol...\n\n(This is a mock LLM response generated by FakeListLLM)"
        ])
        self.auditor = SafetyAuditor()
        
        self.prompt_template = PromptTemplate(
            input_variables=["species", "context", "notes", "allergies", "renal_function"],
            template=(
                "You are an expert PathoMatch AI Clinical Assistant specializing in {species} medicine.\n"
                "Given the following clinical guidelines:\n"
                "---------------------\n"
                "{context}\n"
                "---------------------\n"
                "Patient EHR Constraints:\n"
                "- Notes: {notes}\n"
                "- Allergies: {allergies}\n"
                "- Renal Function: {renal_function}\n\n"
                "Provide a treatment recommendation for this {species} patient, strictly adhering to the guidelines and adjusting for the EHR constraints:"
            )
        )

    def generate_report(self, species: str, notes: str, allergies: str = None, renal_function: str = "Normal") -> dict:
        target_species = species.lower()
        extrapolated = False
        
        # 1. Retrieval with Metadata Filtering
        retriever = self.vectorstore.as_retriever(search_kwargs={'filter': {'species': target_species}})
        docs = retriever.invoke(notes if notes else "General treatment guidelines")
        
        # FIT (Found In Translation) Fallback Logic
        if not docs and target_species != "human":
            extrapolated = True
            retriever = self.vectorstore.as_retriever(search_kwargs={'filter': {'species': "human"}})
            docs = retriever.invoke(notes if notes else "General treatment guidelines")
        
        context_text = "\n\n".join([doc.page_content for doc in docs])
        
        # 2. Format Prompt with EHR Context
        prompt = self.prompt_template.format(
            species=species, 
            context=context_text, 
            notes=notes,
            allergies=allergies or "None reported",
            renal_function=renal_function
        )
        
        # 3. Generate response
        response = self.llm.invoke(prompt)
        
        # 4. LLM-as-a-Judge Safety Audit
        audit_result = self.auditor.evaluate(docs, response)
        
        return {
            "retrieved_documents": [doc.page_content for doc in docs],
            "llm_prompt": prompt,
            "llm_response": response,
            "extrapolated_from_human": extrapolated,
            "safety_audit": audit_result
        }
