import os
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_core.prompts import PromptTemplate
from langchain_community.llms.fake import FakeListLLM

class RAGPipeline:
    def __init__(self):
        # Point to the persistent ChromaDB directory
        db_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'data', 'processed', 'chromadb')
        
        # Load the same embedding model
        self.embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
        
        # Load the persistent Chroma store
        self.vectorstore = Chroma(persist_directory=db_dir, embedding_function=self.embeddings)
        
        # Set up a Mock LLM for local testing without downloading a 14GB model
        self.llm = FakeListLLM(responses=[
            "Based on the retrieved clinical guidelines, here is the recommended treatment protocol...\n\n(This is a mock LLM response generated by FakeListLLM)"
        ])
        
        # Create the RAG prompt template
        self.prompt_template = PromptTemplate(
            input_variables=["species", "context", "notes"],
            template=(
                "You are an expert PathoMatch AI Clinical Assistant specializing in {species} medicine.\n"
                "Given the following clinical guidelines:\n"
                "---------------------\n"
                "{context}\n"
                "---------------------\n"
                "Patient Notes: {notes}\n\n"
                "Provide a treatment recommendation for this {species} patient:"
            )
        )

    def generate_report(self, species: str, notes: str) -> dict:
        """
        Retrieves species-specific guidelines and generates a clinical report.
        """
        # Convert species to lowercase to match our metadata tags
        target_species = species.lower()
        
        # 1. Retrieval with Metadata Filtering! (The "One Health" Safety Feature)
        retriever = self.vectorstore.as_retriever(
            search_kwargs={'filter': {'species': target_species}}
        )
        docs = retriever.invoke(notes if notes else "General treatment guidelines")
        
        # Combine retrieved document text
        context_text = "\n\n".join([doc.page_content for doc in docs])
        
        # 2. Format the Prompt
        prompt = self.prompt_template.format(
            species=species, 
            context=context_text, 
            notes=notes
        )
        
        # 3. Generate response using the Mock LLM
        response = self.llm.invoke(prompt)
        
        return {
            "retrieved_documents": [doc.page_content for doc in docs],
            "llm_prompt": prompt,
            "llm_response": response
        }
